### ISSUE TITLE
Where do I PR ? Configuration issue : you can change root_url but you can't change to http due to ssl usage locked to true

### ISSUE THREAD

**Issue by EtienneLaval** [Mangopay/mangopay2-ruby-sdk#118]
Hi ! I'm currently working with the 3.0.25.0 version of the gem. 
I'd like to make a pull request that applies to every version since, where do you want me to suggest it ?

Concerning the changes made : I've changed the root_url in the MangoPay class configuration as it is allowed by the code. My problem is that I've inputed a http adress and that use_ssl parameter (in request function) is set to true in the request so it only works with https. I guess it's a half implemented feature, so I added 

> use_ssl = configuration.root_url[0,5]=="https"

 in lib/mangopay.rb:136 (line 120 in the 3.0.25.0)

The reason i did this is that I've developped a mock of the sandbox api on a local server to avoid the flacky nature of the official sandbox (concerning cards) so that I can implement automated tests of my plateform.

**Comment by mickaelpois** [comment]
Hello @EtienneLaval and sorry for this very late answer.

Feel free to add any PR on this repo that will be reviewed and merged if everything seems fine and tests are OK :)
We're adding on our side some homemades PRs, but our community is free to help us by posting some interesting PRs !

Thanks a lot for your feedback and your proposal 👍 

Mickaël

**Comment by EtienneLaval** [comment]
Well, I'm not currently working on the mongopay part of my project but if i find time to do so,  i'll make a PR ! If I remember well, it was really some trivial stuff !

**Comment by SoloJr** [comment]
@mickaelpois can you close this? I believe it can be closed.
