### ISSUE TITLE
Allow to pass a logger instead of specify a log_file

### ISSUE THREAD

**Issue by nicolas-brousse** [Mangopay/mangopay2-ruby-sdk#120]
In Rails we have `Rails.logger` present by default. In some cases, like if the application is hosted on Heroku or in a container, the logs are generally sent to `STDOUT`.

It could be nice to be able to configure directly the logger instead of specifying a file path.

Most of ruby gem do it this way, like [`rack-timeout`](https://github.com/heroku/rack-timeout/blob/master/doc/logging.md#logging) for example.

If you are agree with this, I may try to found some time and work on a PR if you want.

**Comment by mickaelpois** [comment]
Hello @nicolas-brousse,

Thanks for pointing this up, very appreciated 👍 
It could be a nice add to our SDK, that's true.
Feel free to propose any PR on this repo whenever you want, I'll be very happy to review it (and I guess our community will too), merge it and release it on a new version !

Mickaël
