### ISSUE TITLE
This account has been temporarily locked for security reasons. Please try again later.

### ISSUE THREAD

**Issue by righen** [Mangopay/mangopay2-ruby-sdk#128]
{"error"=>"unauthorized_client", "error_description"=>"This account has been temporarily locked for security reasons. Please try again later.", "Code"=>"400", "Url"=>"/v2.01/oauth/token"}

Using Ruby on Rails.

**Comment by npotier** [comment]
Hello @righen unfortunately your question doesn't have any answer, and I am facing the same issue as you. 

Did you finally had an explanation about this error message ? I can't find any documentation about it.

**Comment by licanulla** [comment]
Same here.

**Comment by hugohow** [comment]
Same here, in development mode

**Comment by hugohow** [comment]
It was an issue with my initializers

```
MangoPay.configure do |c|
  c.preproduction = Rails.env.development? || Rails.env.test?
  c.client_id = ENV["MANGOPAY_CLIENT_ID"]
  c.client_passphrase = ENV["MANGOPAY_CLIENT_PASSPHRASE"]
end
```

you have to check if the value of preproduction is correct

**Comment by Name-less** [comment]
Hello,
I have the same problem on my account, did you find a solution ?

**Comment by fredericdelordm** [comment]
Hello @Name-less,

You should contact the support team with your clientID. It's not a SDK issue.
