### ISSUE TITLE
undefined method `create' for MangoPay::Client:Class when rails generate

### ISSUE THREAD

**Issue by thomas6791** [Mangopay/mangopay2-ruby-sdk#130]
Hi, when i use rails generate mangopay:install CLIENT_ID CLIENT_NAME CLIENT_EMAIL,
i get this message in my terminal:
Running via Spring preloader in process 2119
undefined method `create' for MangoPay::Client:Class

Have you a solution or clearly instructions to install correctly mangopay with a sandbox account?

**Comment by Mate2xo** [comment]
+1

**Comment by charleshenriponiard** [comment]
+1

**Comment by SoloJr** [comment]
Hello @charleshenriponiard, @Mate2xo 

Can you please tell us what is the full environment used by you so we can test this issue?

Regards,
Mircea
