### ISSUE TITLE
Changed server IP, how does it affect Mango's Api ?

### ISSUE THREAD

**Issue by jay-lay** [Mangopay/mangopay2-ruby-sdk#135]
Hello all,

I have payment failure in 9 cases out of 10. Not really a common pattern between these failures.
Someone suggested me to look into the IP address.
I have moved my website to a bigger server and therefore changed my IP address.

Could that be the reason?

Where do you suggest I look to change the new ip ?

I am not a dev though i put my hand into it everyday, trying my best working with logic... I had looked into the files to check if i spotted and ip written somewhere, and I did not find it.

I will be grateful  for life for your help !

**Comment by mickaelpois** [comment]
Sorry for not giving you any answer.

I can't really help you on that topic, I just can tell you this could be issue with our partner Cloudfare, which rarely "blacklist" some IPs for obscure reasons.

Mickaël
