### ISSUE TITLE
Undocumented removal of client_passphrase in version 3.0.32

### ISSUE THREAD

**Issue by olliebennett** [Mangopay/mangopay2-ruby-sdk#142]
After updating from gem version from `3.0.31` (to `3.0.32`), we get the following error;

```
undefined method `client_passphrase=' for #<MangoPay::Configuration:0x0000a1b2c3d4e5> (NoMethodError)
```

There's already a PR adding some missing documentation around this change; see https://github.com/Mangopay/mangopay2-ruby-sdk/pull/139

Can you please get a process in place when releasing this gems to follow these best-practices?

- Bump more than the `patch` gem version when making a breaking change like this. See [Semantic Versioning](https://semver.org/).
- Update some sort of documentation to give us a clue what to do when updating.

In this specific case, what is `client_apiKey`? Is it expecting the same secret as the `client_passphrase` did in the previous version?

**Comment by mickaelpois** [comment]
Hello @olliebennett 

We're making some updates on our SDK update flow to let this kind of silly issues behind us:
- CHANGELOG.md file has been added and will highlight breaking changes.
- Versioning will be enhanced from the moment our new 4.0 version will be merged on master (very soon).
- Our official doc website (docs.mangopay.com) will be revamped in 2020 and will better highlight technical aspects for each language we are esupporting.
- Last but not least, `client_apiKey` is the same secret as `client_passphrase`, this is "just" a wording update
