### ISSUE TITLE
Getting `MangoPay::ResponseError: The authorization credentials are not valid` after running several tests

### ISSUE THREAD

**Issue by jfloff** [Mangopay/mangopay2-ruby-sdk#148]
I'm running my test battery and I'm finding out that after a while, the MangoPay API starts returning a `MangoPay::ResponseError: The authorization credentials are not valid` exception. I'm pretty sure I have the right credentials because I can run multiple tests in a row, but after a while this is the return. I don't know if I'm issuing too many requests in sequence, but if that's the case then I was expecting a throttled message, not a wrong credentials reply.

**Comment by mickaelpois** [comment]
@jfloff Are you always facing this issue ?
Could you give us more details on this (requests and responses, execution time) ?

**Comment by jfloff** [comment]
I haven't done this in a while because I started using VCR gem for my specs, but if I force new requests I'm still facing that. The pattern is what I described above, it works fine then after multiple specs running it stops workings and returns that error. To me it seems a throttling issue, but the error message does not match that.

**Comment by SoloJr** [comment]
Hi @jfloff 

As many times as I ran the tests, not even once I got an error...

**Comment by jfloff** [comment]
I will try to get a full log the next time I can replicate this issue. We can close for now and reopen when I get that log.

**Comment by jfloff** [comment]
Yesterday running tests I found the error yet again:

```
Failure/Error:
       mangopay_operation = MangoPay::NaturalUser.create({
         Email: self.email,
         FirstName: self.first_name,
         LastName: self.last_name,
         Address: address,
         Birthday: self.birth_date.to_time.to_i,
         Nationality: self.country,
         CountryOfResidence: address[:Country],
       })

     MangoPay::ResponseError:
       The authorization credentials are not valid
     # /app/heroku/ruby/bundle/ruby/2.6.6/gems/mangopay-3.0.32/lib/mangopay.rb:148:in `request'
     # /app/heroku/ruby/bundle/ruby/2.6.6/gems/mangopay-3.0.32/lib/mangopay/http_calls.rb:13:in `create'
     # ./app/models/user.rb:709:in `block in mangopay_create_natural_user'
```

**Comment by jfloff** [comment]
I've updated the previous message with the VCR I recorded on my tests with this exact problem

**Comment by jfloff** [comment]
For future reference this is due to MGP `oauth/token` request. What happens is that on a first run VCR records the `oauth/token` request. But when you record new episodes at a later date (`VCR=new_episodes`) that token is expired, and since that token is replayed by VCR you get an unauthorized reply. 

As a solution, either reply the whole spec or manually remove the token request from your VCR tape and record let VCR record new episodes (hence recording both the new token and the new request)
