### ISSUE TITLE
NoMethodError undefined method `body' for nil:NilClass on Net::ReadTimeout error

### ISSUE THREAD

**Issue by laurynas** [Mangopay/mangopay2-ruby-sdk#167]
When logging is enabled and `Net::ReadTimeout` error occurs, `do_request_with_log` method raises `NoMethodError` error because `res` is `nil`.

https://github.com/Mangopay/mangopay2-ruby-sdk/blob/master/lib/mangopay.rb#L223

**Comment by mangomaxoasis** [comment]
Hi @laurynas,
Looking into it, we'll keep you updated

**Comment by mangomaxoasis** [comment]
Hi @laurynas 
Fix in latest version of SDK 
Cheers,
Max
