### ISSUE TITLE
Effectuer un refund sur un payin

### ISSUE THREAD

**Issue by AlexGrondin10** [Mangopay/mangopay2-ruby-sdk#180]
Bonjour, 

D'après la doc du SDK, on peut seulement fetch un refund et non en créé un. Comment fait-on pour faire un refund sur un payin ?

**Comment by mangomaxoasis** [comment]
Hi @AlexGrondin10 
It's possible, use :
refund = MangoPay::PayIn.refund(payin[‘Id’], {AuthorId: payin[‘AuthorId’]}) 
The base refund call is in https://github.com/Mangopay/mangopay2-ruby-sdk/blob/master/lib/mangopay/http_calls.rb
Cheers

**Comment by mangomaxoasis** [comment]
Hi @AlexGrondin10 
I'm closing this, let me know if the issue persists
