### ISSUE TITLE
Backward-compatibility

### ISSUE THREAD

**Issue by peterb** [Mangopay/mangopay2-ruby-sdk#190]
`MangoPay::Wallet.create` is no longer working after an upgrade from [3.0.33](https://github.com/Mangopay/mangopay2-ruby-sdk/releases/tag/3.0.33) to [3.0.38](https://github.com/Mangopay/mangopay2-ruby-sdk/releases/tag/3.0.38). I'm looking into the details of this and will follow up with reproduction steps.

Presumably you are using [Semver](https://semver.org/) so this upgrade shouldn't have broken backwards-compatibility? 

Is anyone else seeing a similar issue?

**Comment by mangomaxoasis** [comment]
Hi @peterb 
We're looking into it

**Comment by peterb** [comment]
Hi @mangomaxoasis, here are some more details:

```
WebMock::NetConnectNotAllowedError:
  Real HTTP connections are disabled. Unregistered request: POST https://api.sandbox.mangopay.com/v2.01/
...
  You can stub this request with the following snippet:
```

**Comment by peterb** [comment]
I had a look at your [Changelog](https://github.com/Mangopay/mangopay2-ruby-sdk/blob/master/CHANGELOG.md). Since I upgraded from `3.0.33` to `3.0.38`, I would expect it to remain compatible, as the only breaking change seems to be in `3.0.32`?

**Comment by peterb** [comment]
The bug seems to have been introduced in `3.0.34`.

**Comment by peterb** [comment]
It would appear that there's been a change to the sandbox environment. Why is the URL `v2.01`, shouldn't it be `v3.0.38`?

**Comment by fredericdelordm** [comment]
Hello @peterb,

Do you still have this issue ? 

The URL of the latest version of the API is `v2.01` not `v3.0.38`.

**Comment by peterb** [comment]
Hi @fredericdelordm, I see that `v2.01` is the version of the JSON API, and `v3.0.38` is the version of the `mangopay2-ruby-sdk`, thanks for clarifying that!

The more general issue with `mangopay2-ruby-sdk` is that there doesn't seem to be a consistent versioning, if there were breaking changes, I would expect the version to jump from `3.0.33` to `4.0.0` as per [SemVer](https://semver.org)

I'm not maintaining the application that uses the `mangopay2-ruby-sdk` anymore so I'll close this issue.
