### ISSUE TITLE
Which version to use? v3 or v4?

### ISSUE THREAD

**Issue by rokerkony** [Mangopay/mangopay2-ruby-sdk#209]
Hey guys, based on the changelog you wanted to [stop supporting v3 on 29. Mar 2018 when v4 was released](https://github.com/Mangopay/mangopay2-ruby-sdk/releases/tag/v4.0.0.0). Unfortunately, I see only v3 changes in the changelog to continue since then.

Does it mean we should still use the v3 instead?

**Comment by fredericdelordm** [comment]
Hello @rokerkony,

Sorry for the late reply. You should use v3 for now
