### ISSUE TITLE
Can't access "consult_url" in sandbox

### ISSUE THREAD

**Issue by nexxus-vi** [Mangopay/mangopay2-ruby-sdk#224]
I'm trying to get the `consult_url` to check document's pages uploaded, but I get this error:

`=> {"Message"=>"This endpoint is not available for your account", "Type"=>"forbidden_ressource", "Id"=>"redacted", "Date"=>1689245826.0, "errors"=>nil, "Code"=>"403", "Url"=>"/v2.01/CLIENT_ID/KYC/documents/DOCUMENT_ID/consult"}
`

The endpoint where I'm testing the flow is `preproduction`.

**Comment by fredericdelordm** [comment]
Hi @nexxus-vi,

You need to contact the support team to gain access to this endpoint.

Have a nice day,
