### ISSUE TITLE
Improve error handling when logging is enabled

### ISSUE THREAD

**Issue by kaderate** [Mangopay/mangopay2-ruby-sdk#249]
When logging is enabled and an API call fail with another exception that `Net::ReadTimeout`, the following exception is raised:

`NoMethodError: undefined method '*' for nil (NoMethodError) line += "\n [#{(time * 1000).round(1)}ms] 408 Request Timeout #{params}\n" ^`

The cause is the `time` parameter here is not initialized properly and can nil in the case described above:
https://github.com/Mangopay/mangopay2-ruby-sdk/blob/46109ce7ef0497ba6aa9e85ba619de7890b4fd3d/lib/mangopay.rb#L287

**Comment by fredericdelordm** [comment]
Hello @kaderate, thanks for the feedback. We are looking into it.
