### ISSUE TITLE
Link on rubygems.org page

### ISSUE THREAD

**Issue by jlecour** [Mangopay/mangopay2-ruby-sdk#28]
Hi,

The `Source Code` link on the [rubygems.org](https://rubygems.org/gems/mangopay) page points to https://github.com/MangoPay/mangopay, but should point to https://github.com/Mangopay/mangopay2-ruby-sdk

**Comment by hobailey** [comment]
Hi @jlecour, thanks for the heads up :-) We've just updated that and a couple of the other links so they're all much more up to date now!
