### ISSUE TITLE
How to rescue Mangopay error caused by incorrect Iban or Bic?

### ISSUE THREAD

**Issue by davidgeismar** [Mangopay/mangopay2-ruby-sdk#29]
Hi I installed Mangopay payment solution on my rails app. Even though I check the user's Iban and Bic when they update their profile with regular expressions, sometimes when I send the data to Mangopay I get an error message (I guess because even though iban's and bic have a correct format, mangopay finds that they dont actually exist): "One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error. IBAN: IBAN or BIC not valid"

My code for sending theses infos to Mangopay looks like this:

``` 
 def create_mangopay_bank_account
    bank_account = MangoPay::BankAccount.create(current_user.mangopay_natural_user_id, mangopay_user_bank_attributes)
    current_user.bank_account_id = bank_account["Id"]
    current_user.save
  end
```
How can I rescue this error ? I tried something like:
```
 def create_mangopay_bank_account
    if MangoPay::BankAccount.create(current_user.mangopay_natural_user_id, mangopay_user_bank_attributes)
      bank_account = MangoPay::BankAccount.create(current_user.mangopay_natural_user_id, mangopay_user_bank_attributes)
      current_user.bank_account_id = bank_account["Id"]
      current_user.save
    else
      redirect_to user_path
  end
```
but it doesnt work...

**Comment by javiercr** [comment]
From my experience, validating the IBAN is a pain in the ass. Even if you validate with reg exps (the ones that MangoPay gives you in the errors), you'll still find random errors with some invalid bank accounts.

You can try something like this:

```ruby
def create_mangopay_bank_account
  bank_account = MangoPay::BankAccount.create(current_user.mangopay_natural_user_id, mangopay_user_bank_attributes)
  current_user.bank_account_id = bank_account["Id"]
  current_user.save
rescue MangoPay::ResponseError => e
  # do something here to inform your user his bank account is not valid
end
````

**Comment by davidgeismar** [comment]
thanks @javiercr ! this worked like a charm ! I need to learn more about "rescue" in rails
