### ISSUE TITLE
Need a link from Card_ID to card registration

### ISSUE THREAD

**Issue by aug-riedinger** [Mangopay/mangopay2-ruby-sdk#30]
I can fetch a Card Registration : `MangoPay::CardRegistration.fetch(<ID>)`, from a User, I can find a Card, but from a card I can't reach the Card Registration to analyse why the card is in state `INVALID`.

That would be very useful (I'm aware this is API related, and not SDK, but that's my interface to make tech feedbacks).

**Comment by hobailey** [comment]
Hi @aug-riedinger, the Card will be INVALID because of a failed payment attempt - if there was a problem at the registration stage, you wouldn't have received a CardId :-)

**Comment by aug-riedinger** [comment]
Makes sense. I need to investigate further then.
