### ISSUE TITLE
Card Registration Kit in the gem

### ISSUE THREAD

**Issue by tildedash** [Mangopay/mangopay2-ruby-sdk#31]
Hello,

I am testing your solution in a RoR project and I wonder why you did not include the card registration JS kit (at least the minified one) in the gem.

I had to host it myself in the RoR project so if the JS kit has any changes, I will still get an obsolete one in my project.

Another solution is to wrap the JS kit in another gem (like backbone : https://github.com/codebrew/backbone-rails ).

Finally, providing a minified version hosted by Mangopay itself (like Stripe do: https://js.stripe.com/v2/) is a good solution too.

Regards

**Comment by javiercr** [comment]
The [Card Registration Kit](https://github.com/Mangopay/cardregistration-js-kit) is distributed as a [bower package](https://github.com/Mangopay/cardregistration-js-kit/blob/master/bower.json). 

Therefore one option to achieve that would be to use [bower-rails](https://github.com/rharriso/bower-rails/) in your Rails project.

In Rails project I usually store the card-registration-kit in `/vendor/assets/javascript`. I am not changing the implementation of the payment processing that often to need bower or a gem.

Hope it helps.

**Comment by hobailey** [comment]
Hi @tildedash, thanks for this feedback and I'm sorry for the delay getting back to you. I totally agree with @javiercr - a bower package would be the best forward for the moment :-)
