### ISSUE TITLE
Idempotency support missing

### ISSUE THREAD

**Issue by rarruda** [Mangopay/mangopay2-ruby-sdk#35]
The latest version of the v2 API supports idempotency-key being set in the request header to avoid operations happening twice:

https://docs.mangopay.com/api-references/idempotency-support/

However there is currently no way trivial way to set that request header on a per request basis on this gem: https://github.com/Mangopay/mangopay2-ruby-sdk/blob/master/lib/mangopay.rb#L82
(or globally not overriding the default values).

Adding support for it in the library would be highly appreciated.

Also having support for fetching results from requests with the idempotency-key set would be nice to have.

**Comment by hobailey** [comment]
Hi @rarruda, thanks for bringing this up - we're already working on adding idempotency support to our SDKs and we're hoping to update them asap.

**Comment by hobailey** [comment]
Hi @rarruda, just to confirm, we'll be updating the SDK with idempotency support within the next week :-)

**Comment by rarruda** [comment]
:+1: Awesome!

**Comment by sergiusz-woznicki** [comment]
Hi, it's done and released: https://github.com/Mangopay/mangopay2-ruby-sdk/releases/tag/v3.0.20

**Comment by laurynas** [comment]
:+1:

**Comment by rarruda** [comment]
:+1:
