### ISSUE TITLE
BankAccount.create requires user_id

### ISSUE THREAD

**Issue by rdupz** [Mangopay/mangopay2-ruby-sdk#38]
Hello,

I'm wondering why `BankAccount.create` asks for `user_id` while the [docs](https://docs.mangopay.com/api-references/bank-accounts/) does not *stars* `UserId` as a required param.

Based on the fetch route, `UserId` should be stared.

Regards,

**Comment by hobailey** [comment]
Hi @rdupz, you're right - this isn't very clear. Since the `UserId` is in the URL, it is of course required :-) I've just updated the docs to reflect this.
