### ISSUE TITLE
petit problème de TOC sur le wiki ruby-sdk

### ISSUE THREAD

**Issue by mikew75** [Mangopay/mangopay2-ruby-sdk#39]
https://github.com/Mangopay/mangopay2-ruby-sdk/wiki

![image](https://cloud.githubusercontent.com/assets/10197024/13845240/e56a9ed6-ec3e-11e5-8426-96206dc90e96.png)

**Comment by hobailey** [comment]
@mikew75 have you ever seen this problem before on Github? It works fine on all pages except the home page, and putting relative or absolute links doesn't make any difference :-(

**Comment by seuros** [comment]
Fixed.
![screen shot 2016-04-20 at 5 03 03 pm 1](https://cloud.githubusercontent.com/assets/2394703/14681628/dd576486-0719-11e6-9d74-a23ffa608773.png)

**Comment by hobailey** [comment]
@seuros Hmm, doesn't seem great still: 
![image](https://cloud.githubusercontent.com/assets/1564439/14681824/0c8cac1c-0723-11e6-9bb5-57684a0e9b54.png)
