### ISSUE TITLE
(UK) Bank Account registration gives no meaningful error message

### ISSUE THREAD

**Issue by olliebennett** [Mangopay/mangopay2-ruby-sdk#43]
When registering a bank account with an incorrect account number (for example, a 9-digit account number instead of the standard 8 digits), no useful error is provided.

The gem raises the following only:

> MangoPay::ResponseError (One or several required parameters are missing or incorrect)

If the sort code is incorrect however, the following (more useful) message is returned:

> One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error. SortCode: The field SortCode must match the regular expression '\d{6}'.

**Comment by hobailey** [comment]
Hi @olliebennett, thanks for bring this up. It's is a known "issue" with the API itself (not the SDK) and is already on the roadmap to be corrected in the next few months :-)
