### ISSUE TITLE
Occasional authorization problems

### ISSUE THREAD

**Issue by hobailey** [Mangopay/mangopay2-ruby-sdk#45]
We've noticed that there can occassionally be sporadic but unexpected authorization problems and after analyse, a huge percentage of these problems are with those using the Ruby SDK. We therefore need to investigate whether the SDK is correctly handling the oauth tokens, and correctly generating new ones when it should.
The [token regeneration logic](https://github.com/Mangopay/mangopay2-ruby-sdk/blob/master/lib/mangopay/authorization_token.rb#L19) seems fine though, so perhaps it's something else.

**Comment by my-kel** [comment]
Hi all,

Do you have found this problem?

Regards.

**Comment by hobailey** [comment]
Hey @my-kel, I'm not quite sure what you mean - do you also have this problem?

**Comment by my-kel** [comment]
@hobailey,

Yes I have this problem since months. This issue has been open because I contacted your client support on 27th of june.

**Comment by hobailey** [comment]
We're hoping that the simple solution of #56 has solved this, so I'll close this for now - but please do let us know via this thread if you still have problems.
