### ISSUE TITLE
After creating an object CardRegistration CardRegistrationURL is always constant.

### ISSUE THREAD

**Issue by dborovsky** [Mangopay/mangopay2-ruby-sdk#46]
I create an object CardRegistration. 

```
card_preregistration = MangoPay::CardRegistration.create({
        UserId: current_user.mangopay_id,
        Currency: "EUR",
        CardType: "CB_VISA_MASTERCARD"
      })
```

get object

```
{"Id"=>"14920184",
 "Tag"=>nil,
 "CreationDate"=>1469881306,
 "UserId"=>"14864666",
 "AccessKey"=>"1X0m87dmM2LiwFgxPLBJ",
 "PreregistrationData"=>"HBalUf7sKsj1NiktfVS7-3qkcqZHmUspHZMm4Ps6963_ee0enbOZtciDVpLf0nYFS4wCy-yiraxeE65tmxOe8A",
 "RegistrationData"=>nil,
 "CardId"=>nil,
 "CardType"=>"CB_VISA_MASTERCARD",
 "CardRegistrationURL"=>"https://homologation-webpayment.payline.com/webpayment/getToken",
 "ResultCode"=>nil,
 "ResultMessage"=>nil,
 "Currency"=>"EUR",
 "Status"=>"CREATED"}
```

Why every time url is fixed? I read documentation: **hould not be posting the card info to a fixed URL, but instead, you should always post it to the CardRegistrationURL that is found in the CardRegistration object for that particular card registration.**

What exactly is the problem?

**Comment by hobailey** [comment]
Hey there, it's normal the URL is constant - but your application should just do the POST to the `CardRegistrationURL` (because it changes between sandbox and production).

**Comment by dborovsky** [comment]
ok. thank you
