### ISSUE TITLE
Update object Registrationcard - status: "Error", Registration data : Invalid format

### ISSUE THREAD

**Issue by dborovsky** [Mangopay/mangopay2-ruby-sdk#47]
```
card_registration = MangoPay::CardRegistration.update(@card_preregistration['Id'], {
        RegistrationData: params['data'],
        Tag: "custom tag"
      })
```
get object:
```
{"Id"=>"14933221",
 "Tag"=>"custom tag",
 "CreationDate"=>1470042272,
 "UserId"=>"14864666",
 "AccessKey"=>"1X0m87dmM2LiwFgxPLBJ",
 "PreregistrationData"=>"HBalUf7sKsj1NiktfVS7-5hcy0wnI7S09u8Mt_wDqjHl4pF_ovjC3sT4rQlD-kkWS4wCy-yiraxeE65tmxOe8A",
 "RegistrationData"=>
  "dAj315t4g0Sq0Zy7Th16sZW8JdlJU9gOvGgqnX8CQYE31RvhjifXGGPRmadJIXl1RhB87FS5SWmLMvSvJBILNJw1oNiYNfR52yME07yw7w0biQkZzsH3JzYmrfS-dnkQ0ftIYwFxOdfmDQ5GtM_cIg",
 "CardId"=>nil,
 "CardType"=>"CB_VISA_MASTERCARD",
 "CardRegistrationURL"=>"https://homologation-webpayment.payline.com/webpayment/getToken",
 "ResultCode"=>"105206",
 "ResultMessage"=>"Registration data : Invalid format",
 "Currency"=>"EUR",
 "Status"=>"ERROR"}
```

Console logs:

```
Started GET "/finialize?data=dAj315t4g0Sq0Zy7Th16sZW8JdlJU9gOvGgqnX8CQYE31RvhjifXGGPRmadJIXl1RhB87FS5SWmLMvSvJBILNJw1oNiYNfR52yME07yw7w0biQkZzsH3JzYmrfS-dnkQ0ftIYwFxOdfmDQ5GtM_cIg" for 10.240.0.181 at 2016-08-01 09:04:33 +0000
Cannot render console from 10.240.0.181! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by PaymentsController#finialize_payment as */*
  Parameters: {"data"=>"dAj315t4g0Sq0Zy7Th16sZW8JdlJU9gOvGgqnX8CQYE31RvhjifXGGPRmadJIXl1RhB87FS5SWmLMvSvJBILNJw1oNiYNfR52yME07yw7w0biQkZzsH3JzYmrfS-dnkQ0ftIYwFxOdfmDQ5GtM_cIg"}
```
Why Registration data is incorrect? Can you explain more? Thank you

**Comment by hobailey** [comment]
You need to include the  "data=" in your `RegistrationData` parameter :-)

**Comment by dborovsky** [comment]
thank you. now display Token input Error? any idea?

**Comment by hobailey** [comment]
Are you doing the POST from your server, or from the user's browser?

**Comment by dborovsky** [comment]
user`s browser

**Comment by hobailey** [comment]
OK, thanks. And are you receiving this error for the card registration or when doing a payment with the card just registered?

**Comment by bodrovis** [comment]
@hobailey We get this error when trying to update the card registration. We are implementing the same scenario as in this example https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/payment.php#L20 So initially we have a form that a user fills with his data like card id, ccv and that stuff. Then we use JavaScript SDK to submit this data to the MangoPay server. We also have an `ajaxURL` set that points to the URL on our server. There is an action set for this URL that should fetch the `_data` param, update card registration and finalize payment, just like here https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/payment.php#L20

**Comment by bodrovis** [comment]
So we say

```ruby
MangoPay::CardRegistration.update(@card_preregistration['Id'], {
  RegistrationData: "data=#{params['data']}",
  Tag: "custom tag"
})
```

**Comment by bodrovis** [comment]
What's interesting, when I try to run sample code here https://docs.mangopay.com/endpoints/v2.01/cards#e179_update-a-card-registration it returns an error with the status code 500.

**Comment by hobailey** [comment]
Hey @bodrovis, that was a bug with the docs - now fixed, but thanks for flagging it up :-)

So you're using the JS card reg kit [here](https://github.com/Mangopay/cardregistration-js-kit/) in conjunction with this Ruby script?
I don't think I've seen a "token input error" from the JS kit before, so at this stage it would easiest to check the logs of exactly what we're receiving from you. Could you send your `ClientId` and the datetime of an example when you had the problem to support@mangopay.com so we can take a closer look?

**Comment by bodrovis** [comment]
Thank you for help, probably we've identified the cause for now...

**Comment by hobailey** [comment]
Great stuff, thanks for the update :-)

**Comment by LANGEL0128** [comment]
> Gracias por la ayuda, parece que hemos identificado la causa por ahora...

Cual era la causa?
