### ISSUE TITLE
Payment with firefox. Server can`t know what return to client.

### ISSUE THREAD

**Issue by dborovsky** [Mangopay/mangopay2-ruby-sdk#51]
Hi

We are implementing the same scenario as in this example https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/paymentDirect/payment.php

PayIn have status SUCCESS. But server return error: 406. See below data from web console firefox.
 
network - xhr: **status**: 406, **method**: get, **getTocken**: http://localhost:3000/finialize?data=5RSy5qslgAQ7I5fkw79Lp0Tn2Q4KxeTcg-d1ngO56EjRGeKzsrLY_XTuRwDm-dX6Pyit6T8LnOAnD6I2V3x-32QC63V6bTZybplzxBXFGSbtzpJt1NIoKcGRMw1Wxiln_uh-M22NjZ6dU5YsJBBYuA

**register_card.coffee**
```
............................................................................
............................................................................
mangoPay.cardRegistration.sendDataWithAjax(
      # URL to capture response
      finialize_url,
      # Card data
      cardData,
      # Result Ajax callback
      (data) ->
        $this.replaceWith('<p> Payment okay</p> </br> <div id="contract_url"><a href="">Return back to project</a></div>')
        $("#contract_url a").attr("href", contract_url)
        
        #doRedirect = -> window.location.href = data['url']
        #setTimeout doRedirect, 2000
          
      (xhr, status, error) ->
        $('body').prepend("<div class='alert alert-warning'>Payment error </div>");
        
        
      
    )

    return false
```

If create payment with google chrome return from server without error.  Maybe can you help why server can`t know what return to client?  Thank you.

**Comment by dborovsky** [comment]
i fixed and close issue

**Comment by hobailey** [comment]
Hi @dborovsky, could you update us with more info about the problem and fix incase its a central problem?

**Comment by dborovsky** [comment]
it was our mistake. with mangopay all ok.

**Comment by hobailey** [comment]
OK, thanks :-)
