### ISSUE TITLE
Latest Version not released?

### ISSUE THREAD

**Issue by DonSchado** [Mangopay/mangopay2-ruby-sdk#52]
Hi,
following this commit https://github.com/Mangopay/mangopay2-ruby-sdk/commit/cb09f62179d199bcb988cd0e1f1f577233accac5 there should be already 3.0.22 but the latest version on rubygems is still 3.0.21 https://rubygems.org/gems/mangopay

**Comment by hobailey** [comment]
Hey @DonSchado, we've just published the latest version to rubygems - sorry for the delay.

**Comment by DonSchado** [comment]
👍
