### ISSUE TITLE
Gem version 3.0.24 has no code...

### ISSUE THREAD

**Issue by my-kel** [Mangopay/mangopay2-ruby-sdk#60]
Hi,

Your gem version 3.0.24 has no code. The size is 4.5 ko on rubygems. Can you push your gem again to rubygems please?

Regards.

**Comment by hobailey** [comment]
Hey, sorry about that guys - not quite sure what happened, but that's resolved now (had to release a new version in the end since there seems to be a RubyGems bug with yanking releases).
