### ISSUE TITLE
KYC Document Page Create requires "Type"?

### ISSUE THREAD

**Issue by olliebennett** [Mangopay/mangopay2-ruby-sdk#63]
We're processing KYC submissions, but the "create page" step is failing.

We're calling `MangoPay::KycDocument.create_page` ([source](https://github.com/Mangopay/mangopay2-ruby-sdk/blob/master/lib/mangopay/kyc_document.rb#L48)) with the ID of our user, the ID of a previously-created document, and a base64-encoded file string.

```
document = MangoPay::KycDocument.create(mangopay_user_id, { 'Type': 'IDENTITY_PROOF' })
MangoPay::KycDocument.create_page(mangopay_user_id, document[:Id], file_base64)
```

The document object is returned with a status of "CREATED" in line 1. However, an exception is thrown when attempting to create the page (line 2):

> One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error. Type: The Type field is required.

There is no reference to the document's type or a page type requirement in the [API docs](https://docs.mangopay.com/endpoints/v2.01/kyc-documents#e208_create-a-kyc-page).

Any ideas?

**Comment by hobailey** [comment]
Hmm, seems strange, this works normally so we'll need to look into this particular case - could you send an email to support@mangopay.com with your ClientId and the time when you made some of these calls so we can check in the logs please? Thanks!
