### ISSUE TITLE
Accessing Rate Limit Stats

### ISSUE THREAD

**Issue by olliebennett** [Mangopay/mangopay2-ruby-sdk#68]
The [API docs around rate limiting](https://docs.mangopay.com/guide/rate-limiting) show the information returned via the API for rate limit tracking; specifically:

- How many calls you're allowed.
- How many calls you have left.
- The time these will next be reset.

I would like to be able to run a script which obeys the rate limit. Is rate limit information provided via the SDK? How might I inspect the response headers (for example), or achieve this some other way?

**Comment by mickaelpois** [comment]
Hello @olliebennett and sorry for this delay !
Rate limit infos will be available ASAP from response headers, we will provide you an update when it will be available !

Have a nice day.

**Comment by my-kel** [comment]
Hi @mickaelpois,

Do you need some help implementing response headers retrieval in this gem?

Regards.

**Comment by mickaelpois** [comment]
Hi @my-kel !

We are fully open to any help with this subject 👍 
Feel free to create a PR with your proposal, we will have a look at it for sure !

**Comment by hobailey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add rate limit headers to SDK](https://trello.com/c/nzk8yWVJ/145-add-rate-limit-headers-to-sdk)

**Comment by mickaelpois** [comment]
Rate limiting support is now available from our latest release, thanks for your patience everyone !

**Comment by olliebennett** [comment]
Excellent, thanks! Perfect implementation - [documentation](https://github.com/Mangopay/mangopay2-ruby-sdk#accessing-ratelimit-headers) for reference.

**Comment by gabriellupu** [comment]
Thanks for your feedback @olliebennett
