### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by pagedegeek** [Mangopay/mangopay2-ruby-sdk#70]
Can you release gem on rubygems with merged PR https://github.com/Mangopay/mangopay2-ruby-sdk/pull/69 ? :)
Thanks !

**Comment by mickaelpois** [comment]
Hi @pagedegeek, 
A new release will be done today, we were waiting for a new major feature to do it.
Thanks for your patience !

**Comment by mickaelpois** [comment]
Hello again @pagedegeek !
New release is now live (see @ https://rubygems.org/gems/mangopay)

**Comment by pagedegeek** [comment]
Thanks :)
