### ISSUE TITLE
MangoPay::ResponseError  (Error this mean of payment for this asked currency has been disabled)

### ISSUE THREAD

**Issue by Gloumy** [Mangopay/mangopay2-ruby-sdk#75]
I've created a Web Payin with different payment methods, Visa, BCMC and PayLib works as expected but MasterPass, Diners, iDeal and Maestro don't. It returns me this error : 
`MangoPay::ResponseError (Error this mean of payment for this asked currency has been disabled error: The method payment MASTERPASS with the ccy EUR is not active for the partner xxxxxxx)`

It works fine in development with my sandbox account, but in production with the live account it raises the error.

Looking in the Mangopay documentation i've found nothing, and didn't have much luck in the gem documentation.

Any ideas what can cause this problem ?

My code for the payin creation :
`def create_payin(card_type, url)
		mango = MangoPay::PayIn::Card::Web.create({
		  AuthorId: @buyer.mangopay_user_id,
		  CreditedUserId: @seller.mangopay_user_id,
		  DebitedFunds: { Currency: 'EUR', Amount: (@booking.price*100) },
		  # Fees: { Currency: 'EUR', Amount: ((@booking.price*0.10)*100)  },
		  Fees: { Currency: 'EUR', Amount: 0},
		  CreditedWalletId: @seller.mangopay_wallet_id,
		  ReturnURL: "#{url}/bookings/result",
		  CardType: card_type,
		  Culture: 'FR',
		  Tag: "booking #{@booking.id}"
		})

		# Save the transaction in booking_transaction
		BookingTransaction::new({booking_id: @booking.id, transaction_id: mango.fetch('Id')}).save
		
		# return redirect url to payment form
		return mango.fetch('RedirectURL')
	end`

**Comment by hobailey** [comment]
Hey! The payment methods MasterPass, Diners, iDeal and Maestro are not enabled by default, but if you contact our support team (mangopay.com/contact/), they'll be able to look into activating them for you :-)

**Comment by Gloumy** [comment]
Okay thanks !
