### ISSUE TITLE
rails generator is not working

### ISSUE THREAD

**Issue by GeoffTidey** [Mangopay/mangopay2-ruby-sdk#86]
running 
```rails g mangopay:install CLIENT_ID CLIENT_NAME CLIENT_EMAIL```
(with correct parameters)

errors with:
"undefined method `create' for MangoPay::Client:Class"

looks like it was removed in:
https://github.com/Mangopay/mangopay2-ruby-sdk/commit/cb09f62179d199bcb988cd0e1f1f577233accac5#diff-3cc42c41d9e8a81e042a4695ea2ff3bc

I'll generate it manually for now.

BTW. there's also a small spelling mistake here https://github.com/Mangopay/mangopay2-ruby-sdk/blob/master/lib/generators/mangopay/install_generator.rb#L10
it should be your not you're

**Comment by GeoffTidey** [comment]
ha just seen https://github.com/Mangopay/mangopay2-ruby-sdk/issues/79
serves me right for looking at the code

**Comment by hobailey** [comment]
Thanks for the feedback - you can not infact create clients through the SDK any longer and this must be done via the site - we'll get this script updated to avoid confusion :-)
