### ISSUE TITLE
cardregistrationkit.js + mangopay2-ruby-sdk into rails examples

### ISSUE THREAD

**Issue by GeoffTidey** [Mangopay/mangopay2-ruby-sdk#87]
Hi,

Wondering if you have any examples (or best practice notes) of integrating cardregistrationkit.js & mangopay2-ruby-sdk into a rails project?

I see there is this https://github.com/Mangopay/mangopay2-php-sdk/tree/master/demos

but it's PHP :/

**Comment by mickaelpois** [comment]
Hello @GeoffTidey and sorry for the late answer.
We do not have ay example yet, I'll try to see if there's a way for us (and a little bit time to be honest) to make another example.

Sorry for that.

Mickaël
