### ISSUE TITLE
Possibility to get existing user with something else than userId ?

### ISSUE THREAD

**Issue by timott29** [Mangopay/mangopay2-ruby-sdk#92]
Hi,

I would like to check if user exist before create it.
One thing I did not find on the doscumentation is if it mandatory to store into my DB the mangopay userId or if I can search for it based for exemple on email adress (unique on my DB). 

Best for me will be of course to not store new information regarding external system (mangopay).

Regards

**Comment by mickaelpois** [comment]
Hello @timott29 

It's an very useful feature that we are considering, but not in a short term view.
Before bringing you (and every people using Mangopay) this, we do have to think about the best way to offer a powerful search without any performance issue.

We will keep you posted about any update regarding this feature !

Mickaël

**Comment by SoloJr** [comment]
@mickaelpois is there anything to do with this? In the docs it seems that nothing was implemented.

**Comment by mangomaxoasis** [comment]
Hi @timott29,
As mentioned by @mickaelpois search by email is not on our short term roadmap.
Regards,
Max
